title: xchainjs
author: thorchain community
url: https://xchainjs.org
lang: en
description: xchainjs is a library with a common interface for multiple blockchains, built for simple and fast integration for wallets and more. 

logo: "<img src='assets/img/logo.png' width='80px' height='80px'/>"
favicon: "assets/img/logo.png"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - vendor